server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://mysql-auth:3306/auth_db
    username: auth_user
    password: auth_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: auth-service
            client-secret: YXYqwGWQYHUjbqWkpesJg7JENkNaO7HC
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            authorization-uri: http://keycloak:8084/auth/realms/ecommerce/protocol/openid-connect/auth
            token-uri: http://keycloak:8084/auth/realms/ecommerce/protocol/openid-connect/token
            user-info-uri: http://keycloak:8084/auth/realms/ecommerce/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8084/auth/realms/ecommerce/protocol/openid-connect/certs
            user-name-attribute: preferred_username

  eureka:
    client:
      serviceUrl:
        defaultZone: http://discovery-server:8761/eureka/
    instance:
      preferIpAddress: true

keycloak:
  auth-server-url: http://keycloak:8084/auth
  realm: ecommerce
  resource: auth-service
  credentials:
    secret: YXYqwGWQYHUjbqWkpesJg7JENkNaO7HC

logging:
  level:
    org.springframework: INFO
    com.ecommerce.auth: DEBUG